### ISSUE TITLE
Clearance violations anomalies

### ISSUE THREAD

**Issue by Alteregoxxx** [freerouting/freerouting#69]
Hello, first of all thanks for maintaining such a great piece of software!
Some info you asked for:

* [ ] What version of freerouting are you using?
**1.4.4**
* [ ] On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit?
**Windows 10 Pro, version: 20H2, build: 19042.1288**
* [ ] What type of file are you working with? Can you attach the actual (DSN) file?
**File extension is .dsn, see attachment**
* [ ] Did you use any command line arguments?
**No**
* [ ] Can you post a screenshot of the problem?
**Find attached the .dsn and the kicad project from which it was generated** 
* [ ] Can you include the latest, related log entries from the .log file?
**See attachment**
* [ ] Please list the detailed steps to reproduce the problem
**Load the attached .dsn file, check violations**
* [ ] What would you expect freerouting to do in this situation?
**That it doesn't list any violation, in other words it should behave the same Kicad does for the attached project**
* [ ] Is fixing this issue critical for your work?
**Yes, autorouting doesn't work correctly due to this fake violations**

About the problem:

Freerouting detects clearance anomalies in the .dsn file generated starting from a Kicad project for which Kicad ERC detect no anomalies. I've encountered this problem in my last three projects and in all of them I was using for the rules a clearance of 6 mils, equivalent to 0.152**4** mm,  and I've noticed that:

1. In the .dsn files exported by Kicad clearance was set to 0.152**5**, that is 1/10000 mm more than the exact clearance (0.152**4**)
2. Freerouting, when importing this same .dsn file, reports in its clearance matrix table a value of 0.152**6** mm,  that is 1/10000 mm more than the clearance requested in the .dsn (0.152**5**) and 2/10000 mm  more than the exact clearance (0.152**4**)

Editing manually the .dsn files, that is changing the  clearance value in it to be 0.152**3**, solved the problem for the first two projects.

Now, in the latter project, the third of the three I mentioned, this trick is not sufficient to get around the problem: this project uses a custom footprint and Freerouting seems to not like it and detects clearance anomalies, while in Kicad all is perfectly fine....

The custom footprint is a simple "interdigitated electrode", in which the digit width is 10 mils and the space between two digits is about 8.5 mils, hence in perfect compliance with the rules for clearance (6mils).

Find attached a zip file containing the problematic Kicad project and the .dsn file generated from it

Hope I was clear in explaining the issue, feel free to ask if that was not the case :-)

[TestSensel.zip](https://github.com/freerouting/freerouting/files/7363304/TestSensel.zip)

**Comment by lynchaj** [comment]
Hi
I have seen this problem before too. In my case what seems to trigger it is building a PCB in KiCAD, exporting the Specctra session (DSN) to FreeRouting, make the routes, export the Specctra (SES) back to KiCAD and then repeat the cycle. When the PCB loads in FreeRouting a second time it will be full of clearance violation errors which were not there before. Very strange behavior.

Thanks, Andrew Lynch

PS, normally I don't "re-export" PCBs back into FreeRouting because of this phenomenon but the board I am working on now I will have to do this repeatedly. So it might be a good example too. It is an expanded backplane with a lot of parallel traces in close proximity.
     On Monday, October 18, 2021, 05:10:27 AM EDT, Alteregoxxx ***@***.***> wrote:  
 
 


Hello, first of all thanks for maintaining such a great piece of software!
Some info you asked for:
   
   -  What version of freerouting are you using?   
1.4.4
   -  On what platform did you run it? Windows, Linux, MacOS? 32-bit or 64-bit?   
Windows 10 Pro, version: 20H2, build: 19042.1288
   -  What type of file are you working with? Can you attach the actual (DSN) file?   
File extension is .dsn, see attachment
   -  Did you use any command line arguments?   
No
   -  Can you post a screenshot of the problem?   
Find attached the .dsn and the kicad project from which it was generated
   -  Can you include the latest, related log entries from the .log file?   
See attachment
   -  Please list the detailed steps to reproduce the problem   
Load the attached .dsn file, check violations
   -  What would you expect freerouting to do in this situation?   
That it doesn't list any violation, in other words it should behave the same Kicad does for the attached project
   -  Is fixing this issue critical for your work?   
Yes, autorouting doesn't work correctly due to this fake violations

About the problem:

Freerouting detects clearance anomalies in the .dsn file generated starting from a Kicad project for which Kicad ERC detect no anomalies. I've encountered this problem in my last three projects and in all of them I was using for the rules a clearance of 6 mils, equivalent to 0.1524 mm, and I've noticed that:
   
   - In the .dsn files exported by Kicad clearance was set to 0.1525, that is 1/10000 mm more than the exact clearance (0.1524)
   - Freerouting, when importing this same .dsn file, reports in its clearance matrix table a value of 0.1526 mm, that is 1/10000 mm more than the clearance requested in the .dsn (0.1525) and 2/10000 mm more than the exact clearance (0.1524)

Editing manually the .dsn files, that is changing the clearance value in it to be 0.1523, solved the problem for the first two projects.

Now, in the latter project, the third of the three I mentioned, this trick is not sufficient to get around the problem: this project uses a custom footprint and Freerouting seems to not like it and detects clearance anomalies, while in Kicad all is perfectly fine....

The custom footprint is a simple "interdigitated electrode", in which the digit width is 10 mils and the space between two digits is about 8.5 mils, hence in perfect compliance with the rules for clearance (6mils).

Find attached a zip file containing the problematic Kicad project and the .dsn file generated from it

Hope I was clear in explaining the issue, feel free to ask if that was not the case :-)

TestSensel.zip

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Alteregoxxx** [comment]
Hello,
I don't mean to be rude, but it would be better if you could avoid quoting my entire post every time you comment, otherwise reading for other users will quickly become a nightmare...hope you' dont mind for this suggestion :-)

That said, it is sufficient to search with a text editor  (I use Notepad++) for the lines having the word "clearance" (without quotes, obviously) in it (they should be only 3) and change the number as for your needs...

I take advantage of this reply for a for a further small observation: looking at some of the violations I see for my .dsn file, the ones attached I mean, to me it seems that Freerouting report clearance errors even for pad to pad and net to pad belonging to the same electrical net...Am I wrong?

**Comment by andrasfuchs** [comment]
I think we had same issue here: #79.

As described there, a workaround with the `-mt 1` seems to be working, could you confirm?

**Comment by andrasfuchs** [comment]
@Alteregoxxx Sorry for the late reply, I'm browsing trough the older issues and having clearance violations is a reoccurring problem.

You are right, there is something strange happening with KiCad (even with the current version 6.0.5) and its DSN exporter.

If I open your project in the PCB Editor and I set the units to millimeters (in View/Units/Mils) and then I open the net classes dialog (in File/Board Setup.../Design Rules/Net Classes) I see the 6 mils clearance as the default rule, and it's correctly displayed as 0.1524 millimeters:
![image](https://user-images.githubusercontent.com/910321/177342805-e1703941-c587-4421-b167-15d92493383b.png)

When I export it as DSN I got 0.1525 as you did:
![image](https://user-images.githubusercontent.com/910321/177343642-e19299e5-5219-4f30-87ac-f3c5a69b5ec5.png)

This must be a bug in the KiCad exporter, I think.

On our part in freerouting we read the values from the DSN file correctly, but something went wrong at a later stage when - for an unknown reason - freerouting wanted to force the clearance values to be even numbers. I changed that logic, so now it will hopefully work better.

The problem with the custom footprints is a separate issue, I think. Polygons read from your DSN are rendered incorrectly. 
I keep this issue open until that is solved too.

**Comment by geejii** [comment]
I am using the Java version of Freerouter v1.6.2 with KiCad (6.0.8-1)-1 on a Mac running macOS Monterey 12.6.

The first time I use the autorouter, and get back the Specctra Session into KiCad, I get multiple clearance violations from the KiCad Design Rules Checker (see attached screen copy "DRC Clearance Violations.jpg").
What is extremely curious is that if I then delete all those tracks with clearance violations (and only those), and then reiterate the {KiCad Specctra DSN Export -> Freerouter DSN Import -> Freerouter autorouter -> Kicad Specctra Session Import} loop, then I get much less (or if lucky no) clearance violations; sometimes I need to reiterate to achieve 0 violations.
Those iterations are very time consuming, and what I do not understand is why Freerouter cannot do it right the first time, if it can do it right after only a few more iterations.

According to the last post in this thread, this issue was supposed to be cleared in Freerouter (version ??), but may be my issue is subtly different ?
Thanks for any help, and congratulation to all the Freerouter collaborators, keep the good work :-).

![DRC Clearance Violations](https://user-images.githubusercontent.com/19374484/194739826-b61079a1-604b-4cfc-b500-3c67f4de1fe5.jpg)

**Comment by andrasfuchs** [comment]
You are absolutely right, this issue is in the top 3 issues that needs to be solved soon.

The reason for this happening isn't totally clear for me either at this point, I have only theories. I'll need to spend probably a day or two on this to understand the mechanics at play. It can be a rounding problem, a strange behavior introduced by multi-threading in the route optimizer (which is nondeterministic, so that would explain that sometimes we have this issue, sometimes we don't on the same board), a bug in the algorithm that shoves the routes or something totally different.

It's planned to be fixed in 1.7, the next major release, but we will have a minor release with smaller fixes and improvements before that one.

I can't give you a time estimate, because I'm the only one who is actively working on freerouting, and I do it on my free time (for free).
A pull request would speed the things up, so if you or anyone else feels like do this, please do, I'll review your PR as soon as I can.

**Comment by Zumili** [comment]
Hey guys, I was just facing the same problem with two new PCBs.

KiCad (64-bit)
Version: (6.0.7), release build
Platform: Windows 10 (build 19043), 64-bit edition, 64 bit, Little endian, wxMSW

Freerouting v1.6.2 (build-date: 2022-07-13)

When removing the "Postroute" option, no clearance violations occur. But no post route means no optimized tracks.

In the end, adding the "-mt 1" parameter for single threaded route optimization "...\freerouting.exe -mt 1"
fixed that problem for me.

**Comment by geejii** [comment]
Congratulations Thomas, you cracked it !!! B-)
I confirm this workaround works perfectly on the Java version of FreeRouting 1.6.2, running on Java 8.351 on a Mac M1 with macOS Monterey 12.6.
I suppose the mono threaded execution may slow somewhat the FreeRouting first execution, but nothing noticeable. And anyway, it is much, much faster than multiple iterations Kicad<->FreeRouting.

The only thing missing for my ultimate bliss is a KiCad+FreeRouting plugin, but I can easily live without it now that only one pass is required.
Again, many thanks and congratulations !

**Comment by andrasfuchs** [comment]
Thank you guys for the investigation, it really helped fixing it in version 1.7.0. It should work now as expected, I close this issue now.

**Comment by lynchaj** [comment]
Hi
I am still seeing this problem with KiCAD 6.0.11 and FreeRouting 1.7.0 (and the latest snapshot)

I export the DSN from KiCAD, load in FreeRouting, and run it to completion (takes about 2 weeks)

I am using command line parameters " -oit 0 -mt 1" on FreeRouting 1.7.0.

However, when I load the re-exported from DSN into FreeRouting again I get almost 1500 clearance violations and 8 incomplete traces.

What am I doing wrong?

This is a huge problem for me because as it is now, I can export the DSN from KiCAD one time, load in FreeRouting and run to completion with no interruptions.  If my computer crashes or has a restart (windows update, etc.) I lose all my work and have to start over again from scratch.  Since this board takes about 2 weeks to fully optimize that really is very, very inconvenient.

I can save the SES and the DSN from within FreeRouting and re-import the SES into KiCAD and there are no problems (or at least no unexpected ones).  If I re-export the DSN to FreeRouting I get a very large number of clearance violations.

I am hoping someone has written a script that can post-process a DSN file to eliminate all of these clearance violations.

It is very frustrating, please help.

Thanks, Andrew Lynch



[processor.Z80.zip](https://github.com/freerouting/freerouting/files/11396436/processor.Z80.zip)

**Comment by andrasfuchs** [comment]
Hi @lynchaj,

I feel your frustration, and I think we must find a way to (1) make regular snapshots so that you don't need to restart again and again and (2) fix the violation issues, they should not happen with the new default settings when route optimization runs on a single thread. 

I have just created two new, separate issues (#190 and #191) for these and I'll look into it before the next release. Please subscribe to them here on GitHub, so that you get regular updates on my progress.

Also, for me to be able to test clearance violations I would need KiCad project files, not just the DSN, so please upload it into #191, so that I can start testing.

Thank you!
